<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Indah Maharani">
<meta name="dcterms.date" content="2023-01-19">

<title>Analisis Pengaruh Produksi, Luas Lahan, dan Harga Kakao Dunia Terhadap Tingkat Ekspor Kakao Indonesia Tahun 2006-2020</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analisis Pengaruh Produksi, Luas Lahan, dan Harga Kakao Dunia Terhadap Tingkat Ekspor Kakao Indonesia Tahun 2006-2020</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Indah Maharani </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 19, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Di era globalisasi saat ini, perdagangan internasional merupakan suatu aspek yang sangat penting yang bisa meningkatkan perekonomian suatu negara. Saat ini, hampir semua negara melakukan perdagangan internasional dengan ekspor maupun impor. Ekspor adalah perdagangan dengan cara mengeluarkan barang dari daerah Pabean (Sutedi, 2014:12). Indonesia merupakan salah satu negara yang melakukan ekspor. Dengan berbagai sumber daya alam yang dimiliki, Indonesia sudah banyak mengekspor komoditas alamnya ke berbagai negara. Salah satunya komoditas perkebunan Indonesia yaitu kakao. Kakao merupakan salah satu komoditas di sektor perkebunan Indonesia yang menjadi andalan ekspor Indonesia. Indonesia merupakan salah satu negara pengekspor kakao terbesar di dunia.</p>
<p>Berdasarkan data dari Buku Statistik Indonesia 2016, ekspor kakao Indonesia pada tahun 2020 mencapai 377.849 ribu ton. Jumlah tersebut mengalami peningkatan dari tahun sebelumnya namun mengalami penurunan jika dibandingkan dengan ekspor di tahun 2006-2010. Penurunan ekspor setelah tahun 2010 tersebut diakibatkan karena jumlah produksi kakao nasional yang juga mengalami penurunan. Namun pada tahun 2018 produksi kakao dapat kembali meningkat dari 585.246 ribu ton di tahun 2015 menjadi 767.280 ribu ton di tahun 2018. Produksi merupakan salah satu faktor penting yang berhubungan dengan jumlah ekspor. Secara teori, Jika produksi mengalami peningkatan maka ekspor juga akan meningkat (Komalasari, 2009 dalam Mejaya 2016).</p>
<p>Jumlah produksi kakao berkaitan dengan luas lahan perkebunan kakao. Jika lahan perkebunan luas maka produksi juga akan meningkat. Namun, berdasarkan data yang diperoleh dari Direktorat Jenderal Pertanian dan Badan Pusat Statistik, produksi kakao Indonesia pada tahun 2017 hanya sekitar 658.399 ribu ton dengan luas lahan 1.720.773 Ha. Angka produksi tersebut lebih kecil dibandingkan dengan tahun sebelumnya dengan luas lahan yang lebih kecil. Selain luas lahan dan produksi, harga dunia juga merupakan salah satu variable yang berpengaruh terhadap jumlah ekspor.</p>
<p>Jika suatu harga suatu barang meningkat maka negara yang berperan sebagai produsen juga akan meningkatkan ekspornya agar memperoleh untung yang lebih banyak (Ghozy et al., 2017). Dari data yang diperoleh dari ICCO, harga kakao dunia pada tahun 2006-2020 mengalami fluktuasi. Pada tahun 2020 harga kakao dunia mencapai US$ 2.369,85 per ton dengan jumlah eskpor sebesar 377.849 ribu ton. Jumlah tersebut meningkat jika dibandingkan dengan tahun 2019 dengan harga yang lebih rendah. Hal ini menunjukkan bahwa harga kakao dunia dapat mempengaruhi jumlah ekspor kakao Indonesia.</p>
<p>Dari latar belakang yang sudah dijelaskan diatas, dapat diketahui bahwa tingkat ekspor Kakao Indonesia pada tahun 2006-2020 bersifat fluktuatif. Hal tersebut dikarenakan ada beberapa faktor yang mempengaruhinya. Faktor-faktor tersebut diantaranya ada produksi, luas lahan, dan harga kakao dunia. Dengan mengetahui faktor-faktor yang dapat mempengaruhi ekspor kakao, para pelaku eksor kakao Indonesia dapat memprediksi dan meningkatkan eskpor kakaonya. Oleh karena itu, Penilitian ini bertujuan untuk menganalisis pengaruh serta hubungan dari produksi, luas lahan, dan harga kakao dunia pada tahun 2006-2020 terhadap tingkat eskpor kakao Indonesia tahun 2006-2020.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Berdasarkan dari latar belakang permasalahan yang sudah dibahas maka penulisan ini akan dibuat pembatasan masalah agar penilitian lebih berfokus kepada hal-hal yang menjadi pembahasan utama saja. Batasan masalah dalam penelitian ini yaitu mengenai faktor-faktor yang dapt mempengaruhi ekspor kakao Indonesia tahun 2006-2020, informasi mengenai perkembangan ekspor kakao Indonesia tahun 2006-2020, Tingkat produksi kakao Indonesia tahun 2006-2020, luas lahan perkebunan kakao Indonesia 2006-2020, harga kakao dunia tahun 2006-2020, dan bagaimana faktor-faktor tersebut dapat mempengaruhi ekspor kakao Indonesia.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<p>Berdasarkan latar belakang masalah yang telah dijelaskan di atas maka rumusan masalah yang terdapat dalam penilitian ini diantaranya yaitu: 1. Bagaimana tingkat perkembangan ekspor kakao Indonesia, tingkat produksi kakao Indonesia, luas lahan perkebunan kakao Indonesia, dan harga kakao dunia dalam periode tahun 2006-2020? 2. Apakah tingkat produksi kakao Indonesia, luas lahan perkebunan kakao Indonesia, dan harga kakao dunia dalam periode tahun 2006-2020 dapat mempengaruhi tingkat ekspor kakao Indonesia?</p>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Pada penilitian ini terdapat beberapa tujuan yang akan dicapai, diantaranya yaitu: 1. Untuk mengetahui tingkat perkembangan ekspor kakao Indonesia, tingkat produksi kakao Indonesia, luas lahan perkebunan kakao Indonesia, harga kakao dunia dalam periode tahun 2006-2020. 2. Untuk mengetahui apakah tingkat produksi kakao Indonesia, luas lahan perkebunan kakao Indonesia, luas lahan perkebunan kakao Indonesia, dan harga kakao dunia dalam periode 2006-2020 dapat mempengaruhi tingkat eskpor kakao Indonesia.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Package yang digunakan dalam metode analisis penelitian ini yaitu sebagau berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WDI) <span class="co"># tambahkan library lain jika diperlukan</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p>2.1 Ekspor Menurut Amir (2004) Ekspor adalah upaya melakukan penjualan komoditas yang kita miliki kepada bangsa lain atau negara asing, dengan mengharapkan pembayaran dalam valuta asing, serta melakukan komoditi dengan memakai bahasa asing. Sedangkan berdasarkan Undang-Undang Nomor 2 Tahun 2009 tentang Lembaga Pembiayaan Ekspor Indonesia dijelaskan bahwa ekpor adalah kegiatan mengeluarkan barang dari daerah pabean Indonesia dan/atau jasa dari Wilayah Republik Indonesia. Setiap negara memiliki suatu kelebihan contohnya memiliki sumber daya alam melimpah yang dapat menghasilkan banyak komoditas.</p>
<p>Komoditas yang dihasilkan suatu negara mungkin juga belum dapat dipakai langsung karena berupa bahan mentah yang memerlukan pengolahan terlebih dahulu dan oleh karena itu, dengan adanya eskpor maka suatu negara dapat mengekspor ke negara yang membutuhkannya sebagai bahan baku (Widjaja &amp; Yani, 2000:1). Tujuan dari kegiatan ekspor yaitu dengan kegitan ekspor suatu negara dapat membuka pasar baru di luar negeri sebagai perluasan pasar domestik dan bagi perusahaan dalam negeri dapat meningkatkan laba perusahaan melalui perluasan pasar serta memperoleh harga jual yang lebih baik (Sutedi, 2014:15).</p>
<p>2.2 Produksi Menurut Drs. Mohammad Hatta (1994), Produksi merupakan seluruh pekerjaan yang menimbulkan guna, memperbesar guna yang ada dan membagikan guna itu di antara orang banyak. Sedangkan menurut Sukanto Rekso Hadiprodjo, M. Com., Ph.D.&nbsp;dan Drs. Indriyo Gito Sudarmo (1993), Produksi merupakan penciptaan atau penambah faedah bentuk, waktu dan tempat atas faktor-faktor produksi sehingga lebih bermanfaat bagi pemenuhan kebutuhan manusia. Komalasari (dalam Mejaya et al., 2016) menyatakan bahwa produksi memiliki hubungan terhadap ekspor yaitu jika produksi meningkat maka volume ekspor juga akan meningkat, dan sebaliknya.</p>
<p>2.3 Luas Lahan Lahan adalah salah satu faktor produksi, tempat dihasilkannya produk pertanian dan banyak sedikitnya hasil produksi sangat dipengaruhi oleh luas sempitnya lahan yang digunakan (Mubyarto, 1989 dalam Hakiki 2019). Dengan banyaknya luas lahan maka produksi akan meningkat. Dengan begitu, lahan juga merupakan salah satu faktor yang dapat mempengaruhi volume ekspor. Semakin luas lahan maka semakin banyak juga kakao yang dapat diproduksi, sehingga dapat meningkatkan volume eskpor kakao (Segarani, 2015).</p>
<p>2.4 Harga Harga merupakan suatu hal yang sangat penting dalam kegiatan bisnis, karena suatu barang yang akan dijual harus ditentukan harganya terlebih dahulu sehingga seluruh pihak dapat memperoleh keuntungan dan mendapatkan hasil yang memuaskan dengan penetapan harga yang telah disetujui (Puspita et al., 2015). Harga adalah sejumlah uang yang dibebankan untuk suatu produk atau jasa dari nilai tukar konsumen atas manfaat yang didapatkan dari penggunaan produk atau jasa tersebut (Kotler dan Armstrong, 2010).</p>
<p>2.5 Kerangka Penelitian Kerangka penelitian dari penulisan ini tertera sebagai berikut:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Kerangka%20penelitian%20eskpor.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">kerangka penelitian</figcaption><p></p>
</figure>
</div>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<p>3.1 Data Penelitian Penelitian ini menggunakan sumber data sekunder berdasarkan deret wakut (time series), tahun 2006-2020. Data yang digunakan bersal dari berbagai sumber diantara yaitu, data dari Badan Pusat Statistik (BPS), dan data dari International Cocoa Organization (ICCO). Analisis penelitian ini juga dilakukan dengan menggunakan data deskriptif yang berasal dari Buku Statistik Kakao Indonesia tahun 2016 dan 2020, dan website resmi Direktorat Jenderal Pertanian.</p>
<p>3.2 Metode Analisis Penelitian ini menganalsis pengaruh dari produksi, luas lahan, dan harga kakao dunia terhadapa tingkat eskpor kakao Indonesia tahun 2006-2020 dengan menggunakan Metode analisis deskriptif. Metode deskriptif adalah metode dengan cara menganalisis data yang berasal dari sumber buku dan jurnal. Penelitian ini juga Menggunakan R sebagai alat bantu pengolahan data. Package apa saja yang digunakan, tuliskan model yang akan digunakan.</p>
<p>penelitian ini menggunakan data multivariat.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'exkakao.xlsx'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat,<span class="fu">aes</span>(<span class="at">x=</span>ekspor,<span class="at">y=</span>produksi)) <span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="co"># setiap nambah command, selalu kasih tanda +</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"tabel 1. pengaruh produksi, lahan, dan harga dunia terhadap ekspor"</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"ekspor, metric ton"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"produksi, metrik ton"</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"sumber: Badan Pusat Statistik"</span>) <span class="co"># yang terakhir ga perlu +</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-mpg" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/fig-mpg-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;1: City and highway mileage for 38 popular models of cars.Color by number of cylinders</figcaption><p></p>
</figure>
</div>
</div>
</div>
<section id="metode-analisis" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.1</span> Metode analisis</h3>
<p>Metode yang dipilih adalah regresi multivariat dengan 3 variabel independen dengan 1 variabel dependen. Penelitian ini bermaksud untuk mencari pengaruh produksi, luas lahan, dan harga kakao terhadap tingkat ekspor kakao Indonesia. Penelitian ini digunakan dengan rumus:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah tingkat ekspor dan <span class="math inline">\(x_t\)</span> adalah produksi, luas lahan, dan harga kakao.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>Kakao merupakan salah satu komoditi perkebunan yang dapat diolah menjadi cokelat. Kakao adalah komoditas yang cukup penting dalan kegiatan perekonomian Indonesia karena kakao merupakan komoditas ekspor Indoneisa yang menjadi penghasil devisa negara terbesar selain minyak dan gas. Indonesia merupakan salah satu negara produsen dan eskportir kakao terbesar ketiga di dunia (Statistik Kakao Indonesia, 2020).</p>
<table class="table">
<thead>
<tr class="header">
<th>Tahun</th>
<th>ekspor (ton)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2006</td>
<td>609.035</td>
</tr>
<tr class="even">
<td>2007</td>
<td>503.522</td>
</tr>
<tr class="odd">
<td>2008</td>
<td>515.523</td>
</tr>
<tr class="even">
<td>2009</td>
<td>535.236</td>
</tr>
<tr class="odd">
<td>2010</td>
<td>552.880</td>
</tr>
<tr class="even">
<td>2011</td>
<td>410.257</td>
</tr>
<tr class="odd">
<td>2012</td>
<td>387.790</td>
</tr>
<tr class="even">
<td>2013</td>
<td>414.092</td>
</tr>
<tr class="odd">
<td>2014</td>
<td>333.679</td>
</tr>
<tr class="even">
<td>2015</td>
<td>355.321</td>
</tr>
<tr class="odd">
<td>2016</td>
<td>330.029</td>
</tr>
<tr class="even">
<td>2017</td>
<td>354.880</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>380.827</td>
</tr>
<tr class="even">
<td>2019</td>
<td>358.481</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>377.849</td>
</tr>
</tbody>
</table>
<p>sumber: Buku Statistik Indonesia 2016</p>
<p>Berdasarkan data yang diperoleh dari Buku Statistik Indonesia 2016, Volume ekspor kakao Indonesia pada tahun 2006 sampai 2020 mengalami kondisi fluktuatif. Pada tahun 2006, volume ekspor kakao Indonesia sebesar 609.035 ribu ton dan jumlah tersebut merupakan jumlah volume ekspor kakao Indonesia terbesar selama periode 15 tahun. Di tahun 2007, ekspor turun menjadi sebesar 503.522 ribu ton turun menjadi 358.481 ribu ton dan ditahun-tahun selanjutnya volume ekspor kakao Indonesia mulai mengalami penurunan. Sampai di tahun 2020 eskpor kakao Indonesia hanya sekitar 377.849 ribu ton.</p>
<p>Banyaknya volume ekspor kakao Indonesia dipengaruhi oleh beberapa faktor salah satunya yaitu faktor produksi. Jika produksi di dalam negeri mengalami peningkatan, maka jumlah yang dapat di ekspor juga akan meningkat. Dewan Kakao Indonesia (Dekaindo) mengatakan bahwa Indonesia merupakan salah satu negara produsen kakao terbesar di dunia setelah Pantai Gading dan Ghana. Produksi kakao Indonesia selama periode 15 tahun bersifat fluktuatif. Hal tersebut juga dikarenakan oleh luas lahan perkebunan kakao Indonesia yang juga fluktuatif selama 15 tahun tersebut.</p>
<table class="table">
<thead>
<tr class="header">
<th>Tahun</th>
<th>Luas Lahan</th>
<th>Produksi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2006</td>
<td>1.219.633</td>
<td>769.386</td>
</tr>
<tr class="even">
<td>2007</td>
<td>1.272.781</td>
<td>740.006</td>
</tr>
<tr class="odd">
<td>2008</td>
<td>1.326.784</td>
<td>803.594</td>
</tr>
<tr class="even">
<td>2009</td>
<td>1.491.808</td>
<td>809.583</td>
</tr>
<tr class="odd">
<td>2010</td>
<td>1.558.153</td>
<td>837.918</td>
</tr>
<tr class="even">
<td>2011</td>
<td>1.638.329</td>
<td>712.231</td>
</tr>
<tr class="odd">
<td>2012</td>
<td>1.639.337</td>
<td>740.513</td>
</tr>
<tr class="even">
<td>2013</td>
<td>1.660.767</td>
<td>720.862</td>
</tr>
<tr class="odd">
<td>2014</td>
<td>1.686.178</td>
<td>728.414</td>
</tr>
<tr class="even">
<td>2015</td>
<td>1.667.337</td>
<td>593.331</td>
</tr>
<tr class="odd">
<td>2016</td>
<td>1.720.773</td>
<td>658.399</td>
</tr>
<tr class="even">
<td>2017</td>
<td>1.653.116</td>
<td>585.246</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>1.611.014</td>
<td>767.280</td>
</tr>
<tr class="even">
<td>2019</td>
<td>1.560.945</td>
<td>734.795</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>1.508.956</td>
<td>720.660</td>
</tr>
</tbody>
</table>
<p>Sumber: Direktorat Jenderal Pertanian, Badan Pusat Statistik</p>
<p>Berdasarkan data yang diambil dari Direktorat Jenderal Pertanian dan Badan Pusat Statistik pada tahun 2006-2011 Luas lahan perkebunan kakao Indonesia mengalami peninglatan yaitu pada tahun 2006 seluas 1.219.633 Ha dan pada tahun 2011 meningkat menjadi seluas 1.638.329 Ha.</p>
<p>Di tahun-tahun selanjutnya luas lahan kakao Indonesia mulai mengalami peningkatan dan juga penurunan. Luas lahan merupakan salah satu faktor pentimg bagi ekspor di sektor perkebunan, karena dengan semakin luasnya lahan perkebunan maka akan semakin besar pula produksinya. Namun, produksi kakao Indonesia tidak terlalu mengikuti peningkatan luas lahan.</p>
<p>Di tahun 2016, Luas lahan kakao mencapai 1.720.773 Ha tetapi produksi di tahun tersebut hanya sebesar 658.399 ton. Berbeda dengan tahun 2010 yang produksinya mencapai 837.918 ton dengan luas lahan 1.558.153 Ha. Hal tersebut dikarenakan tidak semua lahan perkebunan kakao di Indonesia produktif dan dalam beberpa tahunterakhir banyak perkebunan kakao di Indonesia yang telah beralih menjadi perkebunan Kelapa Sawit, Jagung, Padi dan lain-lain (Wijaya, 2020).</p>
<table class="table">
<thead>
<tr class="header">
<th>Tahun</th>
<th>Harga Kakao Dunia(usd)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2006</td>
<td>1.581,14</td>
</tr>
<tr class="even">
<td>2007</td>
<td>1.907,34</td>
</tr>
<tr class="odd">
<td>2008</td>
<td>2.613,70</td>
</tr>
<tr class="even">
<td>2009</td>
<td>2.990,91</td>
</tr>
<tr class="odd">
<td>2010</td>
<td>3.132,98</td>
</tr>
<tr class="even">
<td>2011</td>
<td>2.980,04</td>
</tr>
<tr class="odd">
<td>2012</td>
<td>2.391,86</td>
</tr>
<tr class="even">
<td>2013</td>
<td>2.496,21</td>
</tr>
<tr class="odd">
<td>2014</td>
<td>3.144,86</td>
</tr>
<tr class="even">
<td>2015</td>
<td>3.136,98</td>
</tr>
<tr class="odd">
<td>2016</td>
<td>2.892,16</td>
</tr>
<tr class="even">
<td>2017</td>
<td>2.029,05</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>2.293,79</td>
</tr>
<tr class="even">
<td>2019</td>
<td>2.340,73</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>2.369,85</td>
</tr>
</tbody>
</table>
<p>Sumber: Market Insider, ICCO</p>
<p>Banyaknya volume yang dapat diekspor juga didukung oleh tingkat harga. Jika harga suatu barang naik maka produsen akan meningkatkan penawarannya untuk barang tersebut. Namun, hal tersebut berbanding terbalik dengan konsumen. Jika harga barang mengalami peningkatan maka permintaan akan barang akan mengalami penurunan sehingga harga akan kembali ke titil keseimbangan (Ghozy et al., 2017). Berdasarkan data pada tabel 4.3, harga kakao dunia dari tahun 2006-2020 selalu mengalami penurunan dan peningkatan. Harga kakao dunia di tahun 2006 dan 2007 masih sekitar US$1000 per ton, namun di tahun selanjutnya naik menjadi US$2000 per ton.</p>
<p>Di tahun 2014 harga kakao naik menjadi US$ 3000 per ton, namun di tahun selanjutnya turun kembali. Pada tahun 2020 harga kakao dunia menjadi US$ 2.369,85 per ton dan jumlah ekspor kakao pada tahun tersebut juga ikut meningkat dibandingkan dengan tahun lalu. Jika dilihat dari tabel tersebut, naik dan turunnya harga kakao dunia dapat mempengaruhi ekspor yaitu ketika harga kakao dunia sedang meningkat maka negara pengekspor juga akan meningkatkan ekspornya.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(ekspor<span class="sc">~</span>produksi<span class="sc">+</span>lahan<span class="sc">+</span>harga,<span class="at">data=</span>dat)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ekspor ~ produksi + lahan + harga, data = dat)

Residuals:
   Min     1Q Median     3Q    Max 
-59432 -33181   -163  38261  67340 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)  7.272e+05  2.854e+05   2.548  0.02709 * 
produksi     3.931e-01  2.323e-01   1.693  0.11864   
lahan       -4.322e-01  1.304e-01  -3.314  0.00691 **
harga        3.267e+01  3.639e+01   0.898  0.38860   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 48390 on 11 degrees of freedom
Multiple R-squared:  0.7742,    Adjusted R-squared:  0.7126 
F-statistic: 12.57 on 3 and 11 DF,  p-value: 0.0007086</code></pre>
</div>
</div>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Dari penelitian tersebut, terdapat kekurangan yang terdapat pada data yang digunakan untuk analisis. Kekurangan yaitu data yang berasal dari Badan Pusat Statistik dan Market Insider harus diolah secara manual. Hal tersebut membuat pengolahan data menjadi lebih lama dan sulit.</p>
<p>Berdasarkan dari hasil analisis, maka dapat diketahui bahwa pengaruh dari produksi, luas lahan, dan harga kakao terhadap tingkat ekspor Indonesia yaitu sebagai berikut: 1. 1 ton produksi dapat menambah tingkat eskpor kakao Indonesia sebesar 393,1 ton. Hal tersebut berarti jumlah produksi kakao berpengaruh signifikan terhadap tingkat ekspor kakao Indonesia tahun 2006-2020. 2. setiap 1 Ha luas lahan perkebunan kakao dapat mengurangi 432,2 Ha tingkat ekspor kakao Indonesia. Hal tersebut berarti luas lahan tidak terlalu berpengaruh secara signifikan terhadap tingkat ekspor kakao Indonesia tahun 2006-2020. 3. Setiap 1 USD dari harga dunia kakao dapat menambah tingkat eskpor kakao Indonesia sebesar 32.670 USD. Hal tersebut berarti harga kakao dunia berpengaruh signifikan terhadap tingkat ekspor kakao Indonesia tahun 2006-2020.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Badan Pusat Statistik. (t.t.). Diambil 19 Januari 2023, dari https://www.bps.go.id/publication/2022/11/30/be404f7a76a56887462b5187/statistik-kakao-indonesia-2021.html</p>
<p>Cocoa PRICE Today | Cocoa Spot Price Chart | Live Price of Cocoa per Ounce | Markets Insider. (t.t.). Diambil 19 Januari 2023, dari https://markets.businessinsider.com/commodities/cocoa-price/usd</p>
<p>Ekspor Biji Kakao Anjlok. (t.t.). Diambil 19 Januari 2023, dari https://disbun.kaltimprov.go.id/artikel/ekspor-biji-kakao-anjlok</p>
<p>Mejaya, A. S., Fanani, D., &amp; Mawardi, M. K. (t.t.). PENGARUH PRODUKSI, HARGA INTERNASIONAL, DAN NILAI TUKAR TERHADAP VOLUME EKSPOR.</p>
<p>Puspita, R., Hidayat, K., &amp; Yulianto, E. (t.t.). PENGARUH PRODUKSI KAKAO DOMESTIK, HARGA KAKAO INTERNASIONAL, DAN NILAI TUKAR TERHADAP EKSPOR KAKAO INDONESIA KE AMERIKA SERIKAT.</p>
<p>Segarani, M. S., &amp; Putu Martini Dewi. (2015). Pengaruh Luas Lahan, Jumlah Produksi, dan Kurs Dollar Pada Ekspro Cengkeh di Indonesia. 4(4).</p>
<p>Statistics—International Cocoa Organization. (t.t.). Diambil 19 Januari 2023, dari https://www.icco.org/statistics/</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>